// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-FKbCRRlJtyh41-wVS1AYfK_-Q2F4gGc',
    appId: '1:666208713462:web:c023e224168043a31e0ad7',
    messagingSenderId: '666208713462',
    projectId: 'testing-5dff9',
    authDomain: 'testing-5dff9.firebaseapp.com',
    storageBucket: 'testing-5dff9.appspot.com',
    measurementId: 'G-2YB5B7FG5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUYBMZ9USrF2V8kS5s9TxYD_vKBIT3bCk',
    appId: '1:666208713462:android:f968603fd3742cca1e0ad7',
    messagingSenderId: '666208713462',
    projectId: 'testing-5dff9',
    storageBucket: 'testing-5dff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0I7F1j29AwB-w1PdubCPL1xOGfYwAAQ',
    appId: '1:666208713462:ios:62fedecc86a091631e0ad7',
    messagingSenderId: '666208713462',
    projectId: 'testing-5dff9',
    storageBucket: 'testing-5dff9.appspot.com',
    androidClientId: '666208713462-hj2ccfruae7n1t1n46k9kr9q9hbt609p.apps.googleusercontent.com',
    iosClientId: '666208713462-4tuuqjk4hpl6kqi87habn0in46o8bnt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0I7F1j29AwB-w1PdubCPL1xOGfYwAAQ',
    appId: '1:666208713462:ios:62fedecc86a091631e0ad7',
    messagingSenderId: '666208713462',
    projectId: 'testing-5dff9',
    storageBucket: 'testing-5dff9.appspot.com',
    androidClientId: '666208713462-hj2ccfruae7n1t1n46k9kr9q9hbt609p.apps.googleusercontent.com',
    iosClientId: '666208713462-4tuuqjk4hpl6kqi87habn0in46o8bnt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );
}
